export interface QueryTemplate {
  id: string
  name: string
  description: string
  whenToUse: string
  pitfalls: string
  defaultQuery: string
  defaultField?: string
  esQueryFn: string
  params: Record<string, unknown>
}

export const QUERY_TEMPLATES: QueryTemplate[] = [
  {
    id: 'multi_match_best_fields',
    name: 'multi_match: best_fields',
    description: 'Searches multiple fields and uses the best-scoring field. A tie_breaker adds a fraction of other field scores. Best for queries where one field dominates (e.g., title should beat description).',
    whenToUse: 'Default product search. When the query is most likely to match one strong field.',
    pitfalls: 'With tie_breaker=0 (dismax), multi-field matches get no boost. Set tie_breaker=0.3 to reward multi-field matches without over-weighting them.',
    defaultQuery: 'wireless noise canceling headphones',
    params: { type: 'best_fields', tieBreaker: 0.3, fields: ['title', 'brand', 'description'] },
    esQueryFn: 'multiMatch',
  },
  {
    id: 'multi_match_most_fields',
    name: 'multi_match: most_fields',
    description: 'Sums scores from all matched fields. Useful when the same content is indexed with multiple analyzers (e.g., stemmed + unstemmed). A document matching in both fields is ranked higher than one matching in only one.',
    whenToUse: 'When you have duplicate fields with different analyzers (stem + no-stem). Rewards documents that match with and without stemming.',
    pitfalls: 'IDF bleeding — rare terms appear in more fields, inflating scores. Not good for dissimilar fields like title + description.',
    defaultQuery: 'running shoes',
    params: { type: 'most_fields', fields: ['title', 'description', 'bullet_features'] },
    esQueryFn: 'multiMatch',
  },
  {
    id: 'multi_match_cross_fields',
    name: 'multi_match: cross_fields',
    description: 'Treats all matched fields as one large virtual document. Each query term must appear in at least one field. Great for queries like "Canon 50mm lens" where terms span title, brand, and description.',
    whenToUse: 'Queries that span multiple entity fields, like person name across first_name + last_name, or product queries across brand + model + type.',
    pitfalls: 'Requires all query terms to appear somewhere across the fields, which can be too strict. Not ideal for freeform text search.',
    defaultQuery: 'canon dslr camera lens',
    params: { type: 'cross_fields', fields: ['title', 'brand', 'description', 'bullet_features'] },
    esQueryFn: 'multiMatch',
  },
  {
    id: 'bool_query',
    name: 'bool with must/should/filter',
    description: 'The most powerful query type — composes multiple clauses. must=AND (scores), should=OR (scores), filter=AND (no scoring, cached), must_not=NOT (no scoring).',
    whenToUse: 'Almost every production query. Use filter for in_stock, price range, category. Use must for required terms. Use should for ranking signals.',
    pitfalls: 'Clauses in filter are cached by ES — avoid using now (use now/1d rounding). should with minimum_should_match=0 can produce confusing rankings.',
    defaultQuery: 'gaming laptop',
    params: { must: ['gaming'], filter: ['Electronics'], should: ['rtx', 'nvidia'] },
    esQueryFn: 'boolQuery',
  },
  {
    id: 'match_phrase',
    name: 'match_phrase',
    description: 'Requires all query terms to appear in the field in the exact order with no gaps between them (unless slop > 0). Much stricter than match — low recall but high precision.',
    whenToUse: 'When word order matters: "project manager" should not match "manager of a project". Also good for product names and model numbers.',
    pitfalls: 'Stemming can cause surprises — "running shoes" matches "run shoe" with english analyzer. Use with english_unstemmed for exact phrase matching.',
    defaultQuery: 'noise canceling headphones',
    params: { field: 'description', slop: 0 },
    esQueryFn: 'phraseMatch',
  },
  {
    id: 'match_phrase_slop',
    name: 'match_phrase with slop',
    description: 'Like match_phrase but allows terms to be up to slop positions apart. slop=2 means up to 2 word transpositions or insertions are allowed between adjacent query terms.',
    whenToUse: 'Proximity search — "canon battery grip" should match "canon brand battery grip" with slop=2. Balances precision and recall.',
    pitfalls: 'High slop values degrade into match query behavior. slop=10 is typically the maximum useful value. Lower is more precise.',
    defaultQuery: 'canon battery grip',
    params: { field: 'description', slop: 2 },
    esQueryFn: 'phraseMatch',
  },
  {
    id: 'match_phrase_prefix',
    name: 'match_phrase_prefix',
    description: 'Like match_phrase but the last term is treated as a prefix. "wire" matches "wireless", "wired", etc. Used for search-as-you-type without a dedicated completion field.',
    whenToUse: 'Simple search-as-you-type. Works out of the box without special index configuration, but is slower than completion suggester or edge n-gram.',
    pitfalls: 'Expands the last term to all matching terms in the index — can match hundreds of terms. Use max_expansions to limit. Slow on large indexes.',
    defaultQuery: 'sony mirr',
    params: { field: 'title' },
    esQueryFn: 'matchPhrasePrefixSearch',
  },
  {
    id: 'function_score',
    name: 'function_score',
    description: 'Wraps any query and modifies the score using functions: field_value_factor (boost by field value like popularity), gauss (distance decay), random_score, script_score.',
    whenToUse: 'When you need to blend BM25 relevance with business signals — popularity, recency, price, CTR, or geo distance. The foundation of production ranking at most companies.',
    pitfalls: 'Over-boosting popularity can make fresh/niche products invisible. Normalize your boost factors carefully. Use boost_mode carefully.',
    defaultQuery: 'camera',
    params: { functions: ['field_value_factor:popularity_score', 'gauss:created_at'] },
    esQueryFn: 'functionScore',
  },
  {
    id: 'more_like_this',
    name: 'more_like_this',
    description: 'Finds documents similar to a given document or text by extracting the most distinctive terms and running a query. Used for "related products" and recommendation features.',
    whenToUse: '"Users who viewed this also viewed..." product recommendations, related articles, duplicate detection. Extract interesting terms automatically.',
    pitfalls: 'Highly dependent on min_term_freq and min_doc_freq settings. Stop words and very common terms dilute results. Best results with clean, content-rich text fields.',
    defaultQuery: 'PROD-0001',
    params: { productId: 'PROD-0001' },
    esQueryFn: 'moreLikeThis',
  },
  {
    id: 'wildcard',
    name: 'wildcard / regexp',
    description: 'Pattern matching with * (zero or more chars) or ? (one char). Regexp allows full regex patterns. Very powerful but VERY slow — leading wildcards (*term) scan the entire index.',
    whenToUse: 'Should be avoided in production for user queries. Acceptable for admin tools, batch jobs, or when restricted to non-leading patterns. Use n-gram indexing instead.',
    pitfalls: 'Leading wildcards (*term) are O(N) — they scan every term in the index. Never allow in user-facing search. Always measure query time before deploying.',
    defaultQuery: '*cam*',
    params: { field: 'title' },
    esQueryFn: 'wildcardSearch',
  },
  {
    id: 'prefix',
    name: 'prefix query',
    description: 'Matches documents where the field starts with the given prefix. With index_prefixes enabled, the prefix is pre-indexed making this O(1) instead of O(N) like wildcard.',
    whenToUse: 'SKU prefix search, autocomplete on brand names, part number lookup. Always enable index_prefixes for fields that need this.',
    pitfalls: 'Without index_prefixes, prefix queries scan the index like wildcard. Always check whether index_prefixes is enabled on the field.',
    defaultQuery: 'cam',
    params: { field: 'sku' },
    esQueryFn: 'prefixSearch',
  },
  {
    id: 'constant_score',
    name: 'constant_score',
    description: 'Wraps a filter clause and assigns a constant score to all matching documents. Since filters are cached and score-less, this is very fast for boolean retrieval.',
    whenToUse: 'When relevance ranking doesn\'t matter — show all in-stock items, all items in a category, all items under $50. Much faster than scored queries for pure filtering.',
    pitfalls: 'You lose all ranking information. Usually combine with a rescorer or sort to provide order. The constant boost value rarely matters for pure filtering.',
    defaultQuery: 'in_stock:true',
    params: { filter: 'in_stock', boost: 1.0 },
    esQueryFn: 'constantScore',
  },
  {
    id: 'terms_lookup',
    name: 'terms lookup',
    description: 'Filters documents where a field matches any value in a list. The list can come from another document (cross-index lookup). Used to implement "saved brands", "user favorites", etc.',
    whenToUse: 'User personalization features — "show me products from my saved brands". The lookup document is fetched from another index and cached.',
    pitfalls: 'The terms list is cached per index — very large lists (>10K terms) can cause memory pressure. Use routing to ensure the lookup document is on the right shard.',
    defaultQuery: 'Canon,Nikon,Sony',
    params: { brands: ['Canon', 'Nikon', 'Sony'] },
    esQueryFn: 'termsLookup',
  },
  {
    id: 'bool_rescore',
    name: 'bool + rescore',
    description: 'Two-phase retrieval: retrieve a large candidate set with a fast cheap query, then apply an expensive re-ranking query to only the top N candidates. Classic production pattern.',
    whenToUse: 'When your ideal ranking function is too expensive to apply to all documents. Retrieve top-1000 with BM25, rerank with a vector model or complex script.',
    pitfalls: 'The window_size must be large enough that the best documents are in the first-phase results. If relevant docs aren\'t in top-N, reranking can\'t help them.',
    defaultQuery: 'professional camera',
    params: { windowSize: 50, rescoreField: 'popularity_score' },
    esQueryFn: 'boolRescore',
  },
]
